// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAihvB1yuHvt7ezbwUPOba2PWbD5dBzKHE',
    appId: '1:231825545587:web:a8b253acc4aac694cf0d06',
    messagingSenderId: '231825545587',
    projectId: 'ra7al-f4953',
    authDomain: 'ra7al-f4953.firebaseapp.com',
    storageBucket: 'ra7al-f4953.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN8CXHdoJwPFxrfjmp6G01Ad0qySsxqwY',
    appId: '1:231825545587:android:d305c7f82e7ecbbecf0d06',
    messagingSenderId: '231825545587',
    projectId: 'ra7al-f4953',
    storageBucket: 'ra7al-f4953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaKjSpZToMus4M-NqSOcw7fUp_vSKTrW8',
    appId: '1:231825545587:ios:d7e910ecd3190340cf0d06',
    messagingSenderId: '231825545587',
    projectId: 'ra7al-f4953',
    storageBucket: 'ra7al-f4953.firebasestorage.app',
    iosBundleId: 'com.example.ra7al',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaKjSpZToMus4M-NqSOcw7fUp_vSKTrW8',
    appId: '1:231825545587:ios:d7e910ecd3190340cf0d06',
    messagingSenderId: '231825545587',
    projectId: 'ra7al-f4953',
    storageBucket: 'ra7al-f4953.firebasestorage.app',
    iosBundleId: 'com.example.ra7al',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAihvB1yuHvt7ezbwUPOba2PWbD5dBzKHE',
    appId: '1:231825545587:web:26a5e3f90c5b2e2dcf0d06',
    messagingSenderId: '231825545587',
    projectId: 'ra7al-f4953',
    authDomain: 'ra7al-f4953.firebaseapp.com',
    storageBucket: 'ra7al-f4953.firebasestorage.app',
  );
}
